# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NKTO_Anwser',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.IntegerField(default=0)),
                ('abody', models.CharField(max_length=255)),
                ('aweight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Blacklist',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('adminid', models.IntegerField(default=0)),
                ('effect_time', models.DateField()),
                ('over_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Category',
            fields=[
                ('cateid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Collect',
            fields=[
                ('collid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('gid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Goods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=255)),
                ('eval_price', models.FloatField()),
                ('category', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_GoodsDts',
            fields=[
                ('gdid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(default=0)),
                ('pic', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Purchase',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('gid', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('tran_time', models.DateField()),
                ('tran_place', models.CharField(max_length=255)),
                ('last_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('cateid', models.IntegerField(default=0)),
                ('qbody', models.CharField(max_length=255)),
                ('qweight', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_Session',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=32)),
                ('login_time', models.DateField()),
                ('error_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('icon', models.CharField(max_length=255)),
                ('point', models.IntegerField(default=0)),
                ('last_login_time', models.DateField()),
                ('signup_time', models.DateField()),
                ('type', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NKTO_ViewLog',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('gid', models.IntegerField(default=0)),
                ('view_time', models.DateField()),
            ],
        ),
    ]
