# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkto_blacklist',
            name='effect_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nkto_purchase',
            name='last_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nkto_session',
            name='login_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nkto_user',
            name='last_login_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nkto_viewlog',
            name='view_time',
            field=models.DateField(auto_now=True),
        ),
    ]
