# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171105_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkto_goods',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
